version: "3.8"
services:
  terraform:
    build: .
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    environment:
      - AWS_ACCESS_KEY_ID=your_aws_access_key
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_key
      - AWS_DEFAULT_REGION=eu-west-1